services:
  scraper:
    build: 
      context: src
    environment:
      - DEPLOYMENT_ENV=compose
    ports:
      - 8000:8000
    networks:
      - react-quarkus
    depends_on:
      - postgres
    expose:
      - 8000
  backend:
    build: 
      context: backend
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    depends_on:
      - postgres
      - scraper
    ports:
      - "8080:8080"
    networks:
      - react-quarkus
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
      - POSTGRESQL_DATABASE=quarkus
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  frontend:
    build: 
      context: frontend
    ports:
      - 3000:3000
    networks:
      - react-quarkus
    depends_on:
      - backend
    expose:
      - 3000
networks:
  react-quarkus: {}
volumes:
  postgres-data: {}